"""escalation policies

Revision ID: 0414a77d051d
Revises: 35e58836356a
Create Date: 2026-06-30 21:06:18.206034

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0414a77d051d"
down_revision: str | Sequence[str] | None = "35e58836356a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "escalation_policies",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_escalation_policies_owner_id"), "escalation_policies", ["owner_id"], unique=False
    )
    op.create_table(
        "escalation_steps",
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("delay_minutes", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["notification_channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["policy_id"], ["escalation_policies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_id", "step_order", name="uq_escalation_steps_policy_order"),
    )
    op.create_index(
        op.f("ix_escalation_steps_policy_id"), "escalation_steps", ["policy_id"], unique=False
    )
    op.add_column(
        "problem_events",
        sa.Column("escalated_step", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("problem_events", "escalated_step")
    op.drop_index(op.f("ix_escalation_steps_policy_id"), table_name="escalation_steps")
    op.drop_table("escalation_steps")
    op.drop_index(op.f("ix_escalation_policies_owner_id"), table_name="escalation_policies")
    op.drop_table("escalation_policies")
    # ### end Alembic commands ###
