"""add host_channels

Revision ID: 05b8d67d749f
Revises: 3b0c2fc4cfbf
Create Date: 2026-06-30 17:12:09.422214

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "05b8d67d749f"
down_revision: str | Sequence[str] | None = "3b0c2fc4cfbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "host_channels",
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["notification_channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("host_id", "channel_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("host_channels")
    # ### end Alembic commands ###
