"""add maintenance windows

Revision ID: 2262219b743a
Revises: 3ef3f9905b19
Create Date: 2026-04-20 23:21:12.014736

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2262219b743a"
down_revision: str | Sequence[str] | None = "3ef3f9905b19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenances",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("strategy", sa.Enum("ONCE", "CRON", name="maintenance_strategy"), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cron", sa.String(length=128), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_maintenances_owner_id"), "maintenances", ["owner_id"], unique=False)
    op.create_table(
        "maintenance_monitors",
        sa.Column("maintenance_id", sa.UUID(), nullable=False),
        sa.Column("monitor_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["maintenance_id"], ["maintenances.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["monitor_id"], ["monitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("maintenance_id", "monitor_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("maintenance_monitors")
    op.drop_index(op.f("ix_maintenances_owner_id"), table_name="maintenances")
    op.drop_table("maintenances")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS maintenance_strategy")
