"""problem events

Revision ID: 35e58836356a
Revises: cf5f43837594
Create Date: 2026-06-30 20:45:29.053865

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "35e58836356a"
down_revision: str | Sequence[str] | None = "cf5f43837594"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problem_events",
        sa.Column("trigger_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("trigger_name", sa.String(length=255), nullable=False),
        sa.Column(
            "severity",
            postgresql.ENUM(
                "INFO",
                "WARNING",
                "AVERAGE",
                "HIGH",
                "DISASTER",
                name="alert_severity",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["acknowledged_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trigger_id"], ["triggers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_problem_events_owner_id"), "problem_events", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_problem_events_resolved_at"), "problem_events", ["resolved_at"], unique=False
    )
    op.create_index(
        op.f("ix_problem_events_trigger_id"), "problem_events", ["trigger_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_problem_events_trigger_id"), table_name="problem_events")
    op.drop_index(op.f("ix_problem_events_resolved_at"), table_name="problem_events")
    op.drop_index(op.f("ix_problem_events_owner_id"), table_name="problem_events")
    op.drop_table("problem_events")
    # ### end Alembic commands ###
