"""discovery rules

Revision ID: 3c013fb9a5b6
Revises: e2a6636ea1da
Create Date: 2026-06-30 21:56:10.199412

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3c013fb9a5b6"
down_revision: str | Sequence[str] | None = "e2a6636ea1da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_rules",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("cidr", sa.String(length=64), nullable=False),
        sa.Column("method", sa.Enum("PING", "TCP", name="discovery_method"), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["templates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovery_rules_owner_id"), "discovery_rules", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f("ix_discovery_rules_owner_id"), table_name="discovery_rules")
    op.drop_table("discovery_rules")
    # Drop the enum type the table created (Alembic doesn't do this automatically).
    sa.Enum(name="discovery_method").drop(op.get_bind(), checkfirst=True)
