"""add retries and retry_interval on monitor

Revision ID: 3ef3f9905b19
Revises: daecfdcb43af
Create Date: 2026-04-20 22:59:57.492318

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3ef3f9905b19"
down_revision: str | Sequence[str] | None = "daecfdcb43af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitors", sa.Column("retries", sa.Integer(), server_default="2", nullable=False)
    )
    op.add_column(
        "monitors", sa.Column("retry_interval", sa.Integer(), server_default="20", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitors", "retry_interval")
    op.drop_column("monitors", "retries")
    # ### end Alembic commands ###
