"""add ingestion tokens

Revision ID: 97776cea4d1f
Revises: b1976e4b555e
Create Date: 2026-06-30 15:26:56.966500

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "97776cea4d1f"
down_revision: str | Sequence[str] | None = "b1976e4b555e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_tokens",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "name", name="uq_ingest_tokens_owner_name"),
    )
    op.create_index(
        op.f("ix_ingestion_tokens_owner_id"), "ingestion_tokens", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_tokens_token_hash"), "ingestion_tokens", ["token_hash"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_tokens_token_hash"), table_name="ingestion_tokens")
    op.drop_index(op.f("ix_ingestion_tokens_owner_id"), table_name="ingestion_tokens")
    op.drop_table("ingestion_tokens")
    # ### end Alembic commands ###
