"""add hosts, items and metric history

Revision ID: b037c16b9c73
Revises: 6668dc620fe7
Create Date: 2026-06-30 14:34:11.095481

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b037c16b9c73"
down_revision: str | Sequence[str] | None = "6668dc620fe7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hosts",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "name", name="uq_hosts_owner_name"),
    )
    op.create_index(op.f("ix_hosts_owner_id"), "hosts", ["owner_id"], unique=False)
    op.create_table(
        "items",
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "value_type",
            sa.Enum("FLOAT", "UNSIGNED", "TEXT", name="item_value_type"),
            nullable=False,
        ),
        sa.Column("units", sa.String(length=32), nullable=True),
        sa.Column("interval", sa.Integer(), server_default="60", nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["host_id"], ["hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "key", name="uq_items_host_key"),
    )
    op.create_index(op.f("ix_items_host_id"), "items", ["host_id"], unique=False)
    op.create_table(
        "metric_values",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("value_num", sa.Float(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metric_values_item_collected",
        "metric_values",
        ["item_id", "collected_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_metric_values_item_collected", table_name="metric_values")
    op.drop_table("metric_values")
    op.drop_index(op.f("ix_items_host_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_hosts_owner_id"), table_name="hosts")
    op.drop_table("hosts")
    op.execute("DROP TYPE IF EXISTS item_value_type")
    # ### end Alembic commands ###
