"""metric trends rollups

Revision ID: cf5f43837594
Revises: 7d2d53401fc9
Create Date: 2026-06-30 19:28:29.527304

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cf5f43837594"
down_revision: str | Sequence[str] | None = "7d2d53401fc9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_trends",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("bucket", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value_min", sa.Float(), nullable=False),
        sa.Column("value_avg", sa.Float(), nullable=False),
        sa.Column("value_max", sa.Float(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "bucket", name="uq_metric_trends_item_bucket"),
    )
    op.create_index(op.f("ix_metric_trends_item_id"), "metric_trends", ["item_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_metric_trends_item_id"), table_name="metric_trends")
    op.drop_table("metric_trends")
    # ### end Alembic commands ###
