"""initial schema

Revision ID: d15b9b166be6
Revises:
Create Date: 2026-04-20 20:51:57.397941

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d15b9b166be6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("auth_provider", sa.Enum("LOCAL", "OIDC", name="auth_provider"), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("oidc_subject", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_oidc_subject"), "users", ["oidc_subject"], unique=False)
    op.create_table(
        "monitors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum("HTTP", "TCP", "PING", "SSL", "DOCKER", name="monitor_type"),
            nullable=False,
        ),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("UP", "DOWN", "PENDING", "PAUSED", name="monitor_status"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_monitors_owner_id"), "monitors", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monitors_owner_id"), table_name="monitors")
    op.drop_table("monitors")
    op.drop_index(op.f("ix_users_oidc_subject"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
    # Alembic autogenerate does not drop Postgres ENUM types created by sa.Enum().
    op.execute("DROP TYPE IF EXISTS monitor_status")
    op.execute("DROP TYPE IF EXISTS monitor_type")
    op.execute("DROP TYPE IF EXISTS auth_provider")
