"""add item is_private

Revision ID: d83103a6d110
Revises: 05b8d67d749f
Create Date: 2026-06-30 17:46:23.739111

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d83103a6d110"
down_revision: str | Sequence[str] | None = "05b8d67d749f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("is_private", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "is_private")
    # ### end Alembic commands ###
