"""add notification channels

Revision ID: daecfdcb43af
Revises: 157f9b404dd7
Create Date: 2026-04-20 21:58:14.693046

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "daecfdcb43af"
down_revision: str | Sequence[str] | None = "157f9b404dd7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_channels",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.Enum("EMAIL", "WEBHOOK", name="channel_type"), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "name", name="uq_channels_owner_name"),
    )
    op.create_index(
        op.f("ix_notification_channels_owner_id"),
        "notification_channels",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "monitor_channels",
        sa.Column("monitor_id", sa.UUID(), nullable=False),
        sa.Column("channel_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["notification_channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["monitor_id"], ["monitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("monitor_id", "channel_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("monitor_channels")
    op.drop_index(op.f("ix_notification_channels_owner_id"), table_name="notification_channels")
    op.drop_table("notification_channels")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS channel_type")
