"""remediation step command

Revision ID: e2a6636ea1da
Revises: 0414a77d051d
Create Date: 2026-06-30 21:44:14.940544

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e2a6636ea1da"
down_revision: str | Sequence[str] | None = "0414a77d051d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "escalation_steps", sa.Column("action_command", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("escalation_steps", "action_command")
    # ### end Alembic commands ###
